image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - verify
  - unit-test
  - integration-test
  - package
  - release
  - docs

before_script:
  - python --version
  - pip --version
  - python -m venv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    - pip install -r requirements.txt

verify:
  stage: verify
  script:
    - prospector
    - bandit -r 2023_assignment1_viewscounter --exclude tests
  only:
    - main

unit-test:
  stage: unit-test
  script:
    - pytest tests/test_unit.py

integration-test:
  stage: integration-test
  script:
    - pytest tests/test_integration.py
  only:
    - main

package:
  stage: package
  script:
    - python increment_version.py minor   # Esegui lo script di incremento della versione
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
  only:
    - main

release:
  stage: release
  script:
    - echo "[pypi]" > ~/.pypirc
    - echo "username = __token__" >> ~/.pypirc
    - echo "password = $TWINE_TOKEN" >> ~/.pypirc
    - twine upload dist/*
  only:
    - main

docs:
  stage: docs
  script:
    - pip install mkdocs
    - mkdocs build --clean
    - mkdir .public
    - cp -r public/* .public
  artifacts:
    paths: 
      - public
      - mkdocs.yaml
    when: on_success
  only:
    - main

