image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test

before_script:
  - virtualenv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    - pip install -r requirements.txt

unit-test:
  stage: test
  script:
    - pytest tests/test_unit.py
