image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - verify
  - unit-test
  - integration-test

before_script:
  - python --version ; pip --version
  - pip install virtualenv
  - python -m venv venv
  - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"

build:
  stage: build
  script:
    - pip install -r requirements.txt

verify:
  stage: verify
  script:
    - prospector  # Esegui l'analisi statica con Prospector
    - bandit -r .  # Esegui l'analisi di sicurezza con Bandit

  artifacts:
    reports:
      codequality: prospector.json  # Salva il report di Prospector come artifact

unit-test:
  stage: unit-test
  script:
    - pytest tests/test_unit.py

integration-test:
  stage: integration-test
  script:
    - pytest tests/test_integration.py
