image: python:latest  # Specifica l'immagine Docker basata su Python utilizzata per le build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"  # Imposta la directory di cache per pip

cache:
  paths:
    - .cache/pip
    - venv/  # Specifica quali directory dovrebbero essere memorizzate nella cache tra le build

stages: # Definizione delle fasi di lavoro
  - build
  - verify
  - unit-test
  - integration-test
  - package
  - release
  - docs

before_script:
  - python --version  # Mostra la versione di Python
  - pip --version  # Mostra la versione di pip
  - pip install --upgrade pip  # Aggiorna pip all'ultima versione
  - python -m venv venv  # Crea un ambiente virtuale Python
  - source venv/bin/activate  # Attiva l'ambiente virtuale

build:
  stage: build
  script:
    - pip install -r requirements.txt  # Installa i requisiti del progetto

prospector:
  stage: verify
  script:
    - prospector  # Esegui l'analisi statica con Prospector
  only: # Esegui questa fase solo quando si fa push su main
  - main  

bandit:
  stage: verify
  script:
    - bandit -r application  # Esegui Bandit per la sicurezza del codice sui package contenenti l'applicazione e la parte di collegamento al database
    - bandit -r database
  only:
  - main  #istruzione che indica che i comandi vengano eseguiti solo se si è sul branch main

unit-test:
  stage: unit-test
  script:
    - pytest tests/test_unit.py  # Esegui i test unitari

integration-test:
  stage: integration-test
  script:
    - pytest tests/test_integration.py  # Esegui i test di integrazione
  only:
    - main  #istruzione che indica che i comandi vengano eseguiti solo se si è sul branch main

package:
  stage: package
  script:
    - git config user.email $GIT_EMAIL #configura l'indirizzo email dell'utente
    - git config user.name $GIT_NAME #configura il nome utente dell'utente
    - git remote add gitlab_origin $GITLAB_REMOTE_URL #aggiunta di un repository remoto
    - python increment_version.py patch #richiamo al metodo per l'aggiornamento della versione del progetto
    - git add setup.py #aggiunge il file setup.py
    - git commit -m "incremento versione" #crea un commit chiamato "incremento versione"
    - git push gitlab_origin HEAD:main -o ci.skip #esegue il push sul main con il comando per non eseguire la pipeline
    - python setup.py sdist bdist_wheel  # Crea i pacchetti distribuibili
  artifacts:
    paths:
      - dist/  # Archivia i pacchetti creati
  only:
    - main  #istruzione che indica che i comandi vengano eseguiti solo se si è sul branch main

release:
  stage: release
  script:
    - echo "[pypi]" > ~/.pypirc  # Crea un file di configurazione per l'upload su PyPI
    - echo "username = $TWINE_USERNAME" >> ~/.pypirc  # Imposta il nome utente per PyPI
    - echo "password = $TWINE_TOKEN" >> ~/.pypirc  # Imposta il token per PyPI
    - twine upload dist/*  # Carica i pacchetti su PyPI
  only:
    - main #istruzione che indica che i comandi vengano eseguiti solo se si è sul branch main

pages:
  stage: docs
  script:
    - mkdocs build --clean #Esegue la pulizia e la compilazione del progetto, generando una nuova versione del sito
    - mkdir .public #crea la directory nascosta ".public"
    - cp -r public/* .public #copia il contenuto della cartella public in .public
  artifacts:
    paths:
      - public
      - mkdocs.yaml
  only:
    - main
