
image: python:3.9
stages:
  - build
  - unit-test
build:
  stage: build
  script:
    - pip install -r requirements.txt
    - pip list
unit-test:
  stage: unit-test
  script:
    - pytest tests/test_unit.py
