image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/  # Aggiungi l'ambiente virtuale alla cache

stages:
  - build
  - verify
  - unit-test
  - integration-test
  - package
  - release

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - source venv/bin/activate

build:
  stage: build
  script:
    - pip install -r requirements.txt
verify:
  stage: verify
  script:
    - prospector  # Esegui l'analisi statica con Prospector
    - bandit -r application/app.py databse/firebase.py --exclude tests

unit-test:
  stage: unit-test
  script:
    - pytest tests/test_unit.py
integration-test:
  stage: integration-test
  script:
    - pytest tests/test_integration.py
package:
  stage: package
  script:
    - python setup.py sdist bdist_wheel
    - ls dist/
  artifacts:
    paths:
      - dist/
release:
  stage: release
  script:
    - source venv/bin/activate
    - echo "[pypi]" > ~/.pypirc
    - echo "username = __token__" >> ~/.pypirc
    - echo "password = $TWINE_TOKEN" >> ~/.pypirc
    - cat ~/.pypirc  # Stampa il contenuto del file .pypirc per scopi di debug
    - twine upload dist/*




