image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/  # Aggiungi l'ambiente virtuale alla cache

stages:
  - build
  - unit-test

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv

build:
  stage: build
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - pip install -r requirements.txt

unit-test:
  stage: unit-test
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - pytest tests/test_unit.py
