image: python:3.9

stages:
  - build
  - unit-test

variables:
  VIRTUAL_ENV: "/venv"  # Modifica il percorso dell'ambiente virtuale in base alla tua configurazione

before_script:
  - python -m venv $VIRTUAL_ENV
  - source $VIRTUAL_ENV/bin/activate

build:
  stage: build
  script:
    - pip install -r requirements.txt

unit-test:
  stage: unit-test
  script:
    - pytest tests/test_unit.py
