image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYPI_USERNAME: __token__
  PYPI_PASSWORD: $PYPI_PASSWORD

cache:
  paths:
    - .cache/pip
    - venv/  # Aggiungi l'ambiente virtuale alla cache

stages:
  - build
  - verify
  - unit-test
  - integration-test
  - package
  - release

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv

build:
  stage: build
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - pip install -r requirements.txt
verify:
  stage: verify
  script:
    - source venv/bin/activate
    - prospector  # Esegui l'analisi statica con Prospector
unit-test:
  stage: unit-test
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - pytest tests/test_unit.py
integration-test:
  stage: integration-test
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - pytest tests/test_integration.py
package:
  stage: package
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - python setup.py sdist bdist_wheel
    - ls dist/
release:
  stage: release
  script:
    - source venv/bin/activate
    - echo "[pypi]" > ~/.pypirc
    - echo "repository = https://upload.pypi.org/legacy/" >> ~/.pypirc
    - echo "username = $PYPI_USERNAME" >> ~/.pypirc
    - echo "password = $PYPI_PASSWORD" >> ~/.pypirc
    - twine upload dist/*
