image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  TWINE_PASSWORD: pypi-AgEIcHlwaS5vcmcCJGIzMGY5OWMwLTdlNmMtNDU3OC05NTZiLTgzMmZkMWE2MTU5MwACKlszLCI5NzZiZjQ1OS1mNTVjLTRiYjEtOTE4Yy04MTQ0ZGE2ZWExZWIiXQAABiCocZ35U1XA9Uf-T4pRGP6OBI9r3bwtK2Kow27SqTfF8A

cache:
  paths:
    - .cache/pip
    - venv/  # Aggiungi l'ambiente virtuale alla cache

stages:
  - build
  - verify
  - unit-test
  - integration-test
  - package
  - release

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv

build:
  stage: build
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - pip install -r requirements.txt
verify:
  stage: verify
  script:
    - source venv/bin/activate
    - prospector  # Esegui l'analisi statica con Prospector
unit-test:
  stage: unit-test
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - pytest tests/test_unit.py
integration-test:
  stage: integration-test
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - pytest tests/test_integration.py
package:
  stage: package
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - python setup.py sdist bdist_wheel
release:
  stage: release
  script:
    - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"
    - twine upload dist/*


