image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - build
  - unit-test

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate  # Attiva l'ambiente virtuale "venv"

build:
  stage: build
  script:
    - pip install -r requirements.txt

unit-test:
  stage: unit-test
  script:
    - source venv/bin/activate  # Assicurati di attivare l'ambiente virtuale "venv"
    - which pytest
    - pytest tests/test_unit.py
